#!/bin/bash
INVENTORY_AUTOGENERATED_FQDN=$(kubectl get httproute inventory -o json | jq -r '.metadata.annotations."application-networking.k8s.aws/lattice-assigned-domain-name"')
echo  $INVENTORY_INTERNAL_FQDN CNAME $INVENTORY_AUTOGENERATED_FQDN
DOMAIN=$(echo $INVENTORY_INTERNAL_FQDN | sed 's/^[^.]*\.//')
HOSTED_ZONE_ID=$(aws route53 list-hosted-zones-by-name --dns-name $DOMAIN --query "HostedZones[0].Id" --output text)
TTL=300
aws route53 change-resource-record-sets --hosted-zone-id $HOSTED_ZONE_ID --change-batch '{
  "Comment": "Creating CNAME record for '"$INVENTORY_INTERNAL_FQDN"'",
  "Changes": [
    {
      "Action": "UPSERT",
      "ResourceRecordSet": {
        "Name": "'"$INVENTORY_INTERNAL_FQDN"'",
        "Type": "CNAME",
        "TTL": '"$TTL"',
        "ResourceRecords": [
          {
            "Value": "'"$INVENTORY_AUTOGENERATED_FQDN"'"
          }
        ]
      }
    }
  ]
}'
